### PR TITLE
chore: Update crossterm to 0.13

### PR DESCRIPTION
**Pull request by ignatenkobrain**

### CODE REVIEW

**Comment by timvisee** [comment]
Thanks!

**Comment by timvisee** [comment]
It appeared that this update broke things. Fixed it in 821956b1277f689b82ae87a1fb79eddcb7f86bfe.

**Comment by ignatenkobrain** [comment]
Thanks for merge & fix.

Would you mind to release new version? Also if you bump to an incompatible version (aka 0.2), please update other crates and make release so we don't have to patch much in Fedora.

Thanks!

**Comment by timvisee** [comment]
Done so just now. Here is the release pipeline for `v0.1.5`:
https://gitlab.com/timvisee/qr2term-rs/pipelines/102419526

>Also if you bump to an incompatible version (aka 0.2), please update other crates and make release so we don't have to patch much in Fedora.

I assume you mean to update crates like `ffsend` that depend on this, on incompatible updates.

**Pull request merged**
